migratedb: Fix binding with SQLAlchemy 2.0
With SQLAlchemy 2.0, pytrainer fails to start when no database is present, with:

	TypeError: MetaData.reflect() missing 1 required positional argument: 'bind'

Both 1.4 and 2.0 support bind as an argument:

https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.MetaData.reflect
https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.MetaData.reflect

https://docs.sqlalchemy.org/en/14/core/reflection.html#reflecting-all-tables-at-once
https://docs.sqlalchemy.org/en/20/core/reflection.html#reflecting-all-tables-at-once

Fixes: https://github.com/pytrainer/pytrainer/issues/280