extensions/fixelevation: Fix xrange reference
This was removed in Python 3 so it fails with:

    NameError: name 'xrange' is not defined. Did you mean: 'range'?

Also need to make sure the steps is `int`.